### PR TITLE
Adding implementation for augmentation of SPCC

### PR DESCRIPTION
**Pull request by jcarrick1**
For augmentation of a sample from the Supernova Photometric Classification Challenge dataset using avocado methods

### CODE REVIEW

**Comment by kboone** [comment]
This is looking good. In our emails you sent me a script that showed how to use this code. Are you planning on including that?

**Comment by jcarrick1** [comment]
I could do if you want. I've been thinking that was specific to how I'd use it, whilst others may want to do things slightly differently using the methods how they see fit, so I can add it if you think it'd be helpful.

By the way, I am taking some time off the next few days so will be slow replying!
________________________________

**Comment by kboone** [comment]
No worries. I was thinking that you could include some kind of a demo to show how to run your code, and ideally reproduce some of the analysis in your paper. That is what I did for the original `avocado` paper. All of the code in the `avocado` folder is general, and the code that is specific to the paper is in the notebook.

I think that we also need your `spcc_sn_data.txt` file for your current implementation.

If you don't want to include a demo or the data file, then I'm happy just pushing things as is with a warning that some tweaks will be necessary to actually run the code on a new analysis. At some point I plan on getting the SPCC data to work with the `Dataset` class which would help a lot with all of this...

**Comment by jcarrick1** [comment]
I have added an example notebook and the metadata txt file for the SPCC.

Everything should now be included, except the SPCC data itself of course. Users would have to specify their directory paths for the data and the list file containing objects to augment.

**Comment by kboone** [comment]
That looks great. A couple minor comments:
- Let's move the data file to a data/ folder instead of having it in the root directory of the repo.
- The notebook is coming in at 24.6 MB due to the large number of plots which is going to massively increase the size of the git repo. Could you rerun it and just show the first 5 or so figures in the notebook (e.g. set `for sn in training_objects[:5]` with `num_augments` set to 1)?

Other than that, I'm happy to go ahead and merge it.

**Comment by jcarrick1** [comment]
I didn't notice how big the notebook was with all those figures!

I've gone ahead and made those changes now, hope that's all good.

**Comment by kboone** [comment]
Looks great, good job!

**Comment by kboone** [comment]
I merged this PR and added a shoutout to your paper in the README. Good luck with the review process!

**Pull request merged**
